from fpdf import FPDF
from datetime import datetime
import json

class SecurityReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'VeriFAI LLM Security Audit Report', 0, 1, 'C')
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'R')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf_report(code_content, llm_analysis, semgrep_results):
    """Generate a professional PDF security report."""
    pdf = SecurityReport()
    pdf.add_page()
    
    # Summary Section
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '1. Executive Summary', 0, 1)
    pdf.set_font('Arial', '', 10)
    summary_text = (
        f"This report contains a detailed security analysis of the provided code. "
        f"The analysis combines static analysis (Semgrep) with AI-driven deep reasoning (LLM)."
    )
    pdf.multi_cell(0, 10, summary_text)
    pdf.ln(5)
    
    # Semgrep Findings
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '2. Static Analysis Findings (Semgrep)', 0, 1)
    pdf.set_font('Arial', '', 10)
    
    findings = semgrep_results.get('results', [])
    if not findings:
        pdf.cell(0, 10, 'No automated vulnerabilities detected by Semgrep.', 0, 1)
    else:
        for i, f in enumerate(findings[:10]): # Limit to top 10 for report
            pdf.set_font('Arial', 'B', 10)
            pdf.cell(0, 10, f"Finding #{i+1}: {f.get('check_id')}", 0, 1)
            pdf.set_font('Arial', '', 9)
            pdf.multi_cell(0, 5, f"Severity: {f.get('severity')}\nLocation: {f.get('path')} (Line {f.get('start', {}).get('line')})\nMessage: {f.get('extra', {}).get('message')}")
            pdf.ln(2)

    # LLM Analysis Section
    pdf.add_page()
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '3. AI-Driven Vulnerability Analysis', 0, 1)
    pdf.set_font('Arial', '', 9)
    # Clean up LLM analysis text for PDF (remove markdown and handle encoding)
    clean_analysis = llm_analysis.replace('**', '').replace('#', '').encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 5, clean_analysis)
    
    # Disclaimer
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 8)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI-assisted security scanner. It should be reviewed by a human security professional before taking any action.")
    
    # In fpdf2, output() returns bytes if no dest is provided
    return bytes(pdf.output())
